### PR TITLE
add profit.png

### PR DESCRIPTION
**Pull request by charapennikaurm**

### CODE REVIEW

**Review by YauheniyaBasaranovich — APPROVED** [review]
Looks great!

Just a couple of notes:
- It would be better if you added filter dropdown designs.
- On review page it would be better to enlarge rating stars fields - from the UX perspective this field is the most important part of the page.
- I also don't see a list of last reviews 🤔

**Comment by charapennikaurm** [comment]
screen
I will enlarge stars and add filter design a bit later. List of last reviews is highlited on the screenshot.

**Comment by YauheniyaBasaranovich** [comment]
> screen
> I will enlarge stars and add filter design a bit later. List of last reviews is highlited on the screenshot.

You can enlarge stars during markup development, for now it's OK to keep as it is.

**Comment by charapennikaurm** [comment]
Ok, thank you.

**Pull request merged**
