### PR TITLE
add task10 html and css

### PR DESCRIPTION
**Pull request by charapennikaurm**

### CODE REVIEW

**Review by YauheniyaBasaranovich — COMMENTED** [review]
Where's the task10? I see some HTML files, if you were supposed to use them instead of SPA, that's incorrect then

**Comment by charapennikaurm** [comment]
> Where's the task10?

It's part of task10, because I had no time to make all task

**Comment by YauheniyaBasaranovich** [comment]
> > Where's the task10?
> 
> It's part of task10, because I had no time to make all task

But you were supposed to organize all the work using JS, without adding additional HTML files

**Comment by charapennikaurm** [comment]
> > > Where's the task10?
> 
> > 
> 
> > It's part of task10, because I had no time to make all task
> 
> 
> 
> But you were supposed to organize all the work using JS, without adding additional HTML files

I misunderstood the task

**Comment by YauheniyaBasaranovich** [comment]
> > > > Where's the task10?
> > 
> > 
> > > 
> > 
> > 
> > > It's part of task10, because I had no time to make all task
> > 
> > 
> > But you were supposed to organize all the work using JS, without adding additional HTML files
> 
> I misunderstood the task

There couldn't be more than 2 for this task in this case, sorry 🙁

**Comment by charapennikaurm** [comment]
> > > > > Where's the task10?
> 
> > > 
> 
> > > 
> 
> > > > 
> 
> > > 
> 
> > > 
> 
> > > > It's part of task10, because I had no time to make all task
> 
> > > 
> 
> > > 
> 
> > > But you were supposed to organize all the work using JS, without adding additional HTML files
> 
> > 
> 
> > I misunderstood the task
> 
> 
> 
> There couldn't be more than 2 for this task in this case, sorry 🙁 

Maybe 4, please

**Comment by charapennikaurm** [comment]
> > > > > > Where's the task10?
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > 
> > 
> > > > 
> > 
> > > > 
> > 
> > > > > It's part of task10, because I had no time to make all task
> > 
> > > > 
> > 
> > > > 
> > 
> > > > But you were supposed to organize all the work using JS, without adding additional HTML files
> > 
> > > 
> > 
> > > I misunderstood the task
> > 
> > 
> > 
> > There couldn't be more than 2 for this task in this case, sorry 🙁 
> 
> Maybe 4, please

It will help me to boost my mark))

**Comment by YauheniyaBasaranovich** [comment]
> > > > > > > Where's the task10?
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > > It's part of task10, because I had no time to make all task
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > >
> > > 
> > > 
> > > > > But you were supposed to organize all the work using JS, without adding additional HTML files
> > > 
> > > 
> > > > 
> > > 
> > > 
> > > > I misunderstood the task
> > > 
> > > 
> > > There couldn't be more than 2 for this task in this case, sorry 🙁
> > 
> > 
> > Maybe 4, please
> 
> It will help me to boost my mark))

We increased some of previous scores, hope that helped 🙂

**Comment by charapennikaurm** [comment]
> > > > > > > > Where's the task10?
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > > It's part of task10, because I had no time to make all task
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > >
> 
> > > > 
> 
> > > > 
> 
> > > > > > But you were supposed to organize all the work using JS, without adding additional HTML files
> 
> > > > 
> 
> > > > 
> 
> > > > > 
> 
> > > > 
> 
> > > > 
> 
> > > > > I misunderstood the task
> 
> > > > 
> 
> > > > 
> 
> > > > There couldn't be more than 2 for this task in this case, sorry 🙁
> 
> > > 
> 
> > > 
> 
> > > Maybe 4, please
> 
> > 
> 
> > It will help me to boost my mark))
> 
> 
> 
> We increased some of previous scores, hope that helped 🙂 

Thanks)

**Pull request merged**
